services:
  playwrightcore:
    image: playwrightcore
    build:
      context: .venv/Lib/site-packages/playwright/driver/package
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
